	state: 
	  time: 0.0
	  h: 0.0
	  g: 0.0
	  depth: 0
	  state vars: [["['is_reachable', 'cell_1_1']", False], ["['is_reachable', 'cell_1_2']", False], ["['is_reachable', 'cell_1_3']", False], ["['is_reachable', 'cell_2_1']", False], ["['is_reachable', 'cell_2_2']", False], ["['is_reachable', 'cell_2_3']", True], ["['is_reachable', 'cell_3_1']", False], ["['is_reachable', 'cell_3_2']", False], ["['is_reachable', 'cell_3_3']", False], ["['is_pickable', 'bread1']", True], ["['is_openable', 'bread1']", False], ["['is_near', 'cell_1_1']", False], ["['is_near', 'cell_1_2']", False], ["['is_near', 'cell_1_3']", False], ["['is_near', 'cell_2_1']", False], ["['is_near', 'cell_2_2']", False], ["['is_near', 'cell_2_3']", False], ["['is_near', 'cell_3_1']", False], ["['is_near', 'cell_3_2']", False], ["['is_near', 'cell_3_3']", False], ["['location', 'bread1', 'cell_1_1']", False], ["['location', 'bread1', 'cell_1_2']", False], ["['location', 'bread1', 'cell_1_3']", False], ["['location', 'bread1', 'cell_2_1']", False], ["['location', 'bread1', 'cell_2_2']", False], ["['location', 'bread1', 'cell_2_3']", False], ["['location', 'bread1', 'cell_3_1']", False], ["['location', 'bread1', 'cell_3_2']", False], ["['location', 'bread1', 'cell_3_3']", True], ["['holding', 'bread1']", False], ["['opened', 'bread1']", False], ["['inside', 'bread1', 'bread1']", False], ["['robot_x']", 1.0], ["['robot_y']", 1.0], ["['prev_robot_x']", -10.0], ["['prev_robot_y']", -10.0], ["['cell_x', 'cell_1_1']", 1.0], ["['cell_x', 'cell_1_2']", 1.0], ["['cell_x', 'cell_1_3']", 1.0], ["['cell_x', 'cell_2_1']", 2.0], ["['cell_x', 'cell_2_2']", 2.0], ["['cell_x', 'cell_2_3']", 2.0], ["['cell_x', 'cell_3_1']", 3.0], ["['cell_x', 'cell_3_2']", 3.0], ["['cell_x', 'cell_3_3']", 3.0], ["['cell_y', 'cell_1_1']", 1.0], ["['cell_y', 'cell_1_2']", 2.0], ["['cell_y', 'cell_1_3']", 3.0], ["['cell_y', 'cell_2_1']", 1.0], ["['cell_y', 'cell_2_2']", 2.0], ["['cell_y', 'cell_2_3']", 3.0], ["['cell_y', 'cell_3_1']", 1.0], ["['cell_y', 'cell_3_2']", 2.0], ["['cell_y', 'cell_3_3']", 3.0], ["['location_x', 'bread1']", 0.0], ["['location_y', 'bread1']", 0.0]]
     0.000:	teleport cell_1_1 cell_2_3	[0.0]
	state: 
	  time: 0.0
	  h: 0.0
	  g: 0.0
	  depth: 1
	  state vars: [["['is_reachable', 'cell_1_1']", False], ["['is_reachable', 'cell_1_2']", False], ["['is_reachable', 'cell_1_3']", False], ["['is_reachable', 'cell_2_1']", False], ["['is_reachable', 'cell_2_2']", False], ["['is_reachable', 'cell_2_3']", True], ["['is_reachable', 'cell_3_1']", False], ["['is_reachable', 'cell_3_2']", False], ["['is_reachable', 'cell_3_3']", False], ["['is_pickable', 'bread1']", True], ["['is_openable', 'bread1']", False], ["['is_near', 'cell_1_1']", False], ["['is_near', 'cell_1_2']", False], ["['is_near', 'cell_1_3']", True], ["['is_near', 'cell_2_1']", False], ["['is_near', 'cell_2_2']", True], ["['is_near', 'cell_2_3']", False], ["['is_near', 'cell_3_1']", False], ["['is_near', 'cell_3_2']", False], ["['is_near', 'cell_3_3']", True], ["['location', 'bread1', 'cell_1_1']", False], ["['location', 'bread1', 'cell_1_2']", False], ["['location', 'bread1', 'cell_1_3']", False], ["['location', 'bread1', 'cell_2_1']", False], ["['location', 'bread1', 'cell_2_2']", False], ["['location', 'bread1', 'cell_2_3']", False], ["['location', 'bread1', 'cell_3_1']", False], ["['location', 'bread1', 'cell_3_2']", False], ["['location', 'bread1', 'cell_3_3']", True], ["['holding', 'bread1']", False], ["['opened', 'bread1']", False], ["['inside', 'bread1', 'bread1']", False], ["['robot_x']", 2.0], ["['robot_y']", 3.0], ["['prev_robot_x']", 1.0], ["['prev_robot_y']", 1.0], ["['cell_x', 'cell_1_1']", 1.0], ["['cell_x', 'cell_1_2']", 1.0], ["['cell_x', 'cell_1_3']", 1.0], ["['cell_x', 'cell_2_1']", 2.0], ["['cell_x', 'cell_2_2']", 2.0], ["['cell_x', 'cell_2_3']", 2.0], ["['cell_x', 'cell_3_1']", 3.0], ["['cell_x', 'cell_3_2']", 3.0], ["['cell_x', 'cell_3_3']", 3.0], ["['cell_y', 'cell_1_1']", 1.0], ["['cell_y', 'cell_1_2']", 2.0], ["['cell_y', 'cell_1_3']", 3.0], ["['cell_y', 'cell_2_1']", 1.0], ["['cell_y', 'cell_2_2']", 2.0], ["['cell_y', 'cell_2_3']", 3.0], ["['cell_y', 'cell_3_1']", 1.0], ["['cell_y', 'cell_3_2']", 2.0], ["['cell_y', 'cell_3_3']", 3.0], ["['location_x', 'bread1']", 0.0], ["['location_y', 'bread1']", 0.0]]
     0.000:	pick bread1 cell_3_3	[0.0]
	state: 
	  time: 0.0
	  h: 0.0
	  g: 0.0
	  depth: 2
	  state vars: [["['is_reachable', 'cell_1_1']", False], ["['is_reachable', 'cell_1_2']", False], ["['is_reachable', 'cell_1_3']", False], ["['is_reachable', 'cell_2_1']", False], ["['is_reachable', 'cell_2_2']", False], ["['is_reachable', 'cell_2_3']", True], ["['is_reachable', 'cell_3_1']", False], ["['is_reachable', 'cell_3_2']", False], ["['is_reachable', 'cell_3_3']", False], ["['is_pickable', 'bread1']", True], ["['is_openable', 'bread1']", False], ["['is_near', 'cell_1_1']", False], ["['is_near', 'cell_1_2']", False], ["['is_near', 'cell_1_3']", True], ["['is_near', 'cell_2_1']", False], ["['is_near', 'cell_2_2']", True], ["['is_near', 'cell_2_3']", False], ["['is_near', 'cell_3_1']", False], ["['is_near', 'cell_3_2']", False], ["['is_near', 'cell_3_3']", True], ["['location', 'bread1', 'cell_1_1']", False], ["['location', 'bread1', 'cell_1_2']", False], ["['location', 'bread1', 'cell_1_3']", False], ["['location', 'bread1', 'cell_2_1']", False], ["['location', 'bread1', 'cell_2_2']", False], ["['location', 'bread1', 'cell_2_3']", False], ["['location', 'bread1', 'cell_3_1']", False], ["['location', 'bread1', 'cell_3_2']", False], ["['location', 'bread1', 'cell_3_3']", False], ["['holding', 'bread1']", True], ["['opened', 'bread1']", False], ["['inside', 'bread1', 'bread1']", False], ["['robot_x']", 2.0], ["['robot_y']", 3.0], ["['prev_robot_x']", 1.0], ["['prev_robot_y']", 1.0], ["['cell_x', 'cell_1_1']", 1.0], ["['cell_x', 'cell_1_2']", 1.0], ["['cell_x', 'cell_1_3']", 1.0], ["['cell_x', 'cell_2_1']", 2.0], ["['cell_x', 'cell_2_2']", 2.0], ["['cell_x', 'cell_2_3']", 2.0], ["['cell_x', 'cell_3_1']", 3.0], ["['cell_x', 'cell_3_2']", 3.0], ["['cell_x', 'cell_3_3']", 3.0], ["['cell_y', 'cell_1_1']", 1.0], ["['cell_y', 'cell_1_2']", 2.0], ["['cell_y', 'cell_1_3']", 3.0], ["['cell_y', 'cell_2_1']", 1.0], ["['cell_y', 'cell_2_2']", 2.0], ["['cell_y', 'cell_2_3']", 3.0], ["['cell_y', 'cell_3_1']", 1.0], ["['cell_y', 'cell_3_2']", 2.0], ["['cell_y', 'cell_3_3']", 3.0], ["['location_x', 'bread1']", 0.0], ["['location_y', 'bread1']", 0.0]]
